apiVersion: v1
kind: Service
metadata:
  name: workout-service
  namespace: trackmygym
spec:
  selector:
    app: workout-service
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  type: ClusterIP