apiVersion: v1
kind: Service
metadata:
  name: stats-service
  namespace: trackmygym
spec:
  selector:
    app: stats-service
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
  type: ClusterIP
